<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251205234928 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE audit_logs (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, action VARCHAR(255) NOT NULL, table_name VARCHAR(255) NOT NULL, record_id INT NOT NULL, ip VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_D62F28589D86650F ON audit_logs (user_id_id)');
        $this->addSql('CREATE TABLE cart_items (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, quantity INT NOT NULL, price NUMERIC(10, 2) NOT NULL, cart_id_id INT NOT NULL, product_id_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_BEF4844520AEF35F ON cart_items (cart_id_id)');
        $this->addSql('CREATE INDEX IDX_BEF48445DE18E50B ON cart_items (product_id_id)');
        $this->addSql('CREATE TABLE carts (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id_id INT NOT NULL, customer_id_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_4E004AAC9D86650F ON carts (user_id_id)');
        $this->addSql('CREATE INDEX IDX_4E004AACB171EB6C ON carts (customer_id_id)');
        $this->addSql('CREATE TABLE customers (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, phone VARCHAR(255) NOT NULL, address VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE notifications (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, body TEXT NOT NULL, type VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE permissions (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, description TEXT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE products (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, sku VARCHAR(255) NOT NULL, description TEXT NOT NULL, price NUMERIC(10, 0) NOT NULL, cost NUMERIC(10, 2) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, category_id_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B3BA5A5A9777D11E ON products (category_id_id)');
        $this->addSql('CREATE TABLE purchase_items (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, quantity INT NOT NULL, cost NUMERIC(10, 2) NOT NULL, purchase_id_id INT NOT NULL, product_id_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_35D56A67AB8F1D7D ON purchase_items (purchase_id_id)');
        $this->addSql('CREATE INDEX IDX_35D56A67DE18E50B ON purchase_items (product_id_id)');
        $this->addSql('CREATE TABLE purchases (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, total NUMERIC(10, 2) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, supplier_id_id INT NOT NULL, user_id_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_AA6431FEA65F9C7D ON purchases (supplier_id_id)');
        $this->addSql('CREATE INDEX IDX_AA6431FE9D86650F ON purchases (user_id_id)');
        $this->addSql('CREATE TABLE role_permissions (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, role_id INT NOT NULL, permission_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_1FBA94E6D60322AC ON role_permissions (role_id)');
        $this->addSql('CREATE INDEX IDX_1FBA94E6FED90CCA ON role_permissions (permission_id)');
        $this->addSql('CREATE TABLE sale_items (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, quantity INT NOT NULL, price NUMERIC(10, 2) NOT NULL, sale_id_id INT NOT NULL, product_id_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_31C2B1CEAF98C6D4 ON sale_items (sale_id_id)');
        $this->addSql('CREATE INDEX IDX_31C2B1CEDE18E50B ON sale_items (product_id_id)');
        $this->addSql('CREATE TABLE sales (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, total NUMERIC(10, 2) NOT NULL, payment_method VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, customer_id_id INT NOT NULL, user_id_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6B817044B171EB6C ON sales (customer_id_id)');
        $this->addSql('CREATE INDEX IDX_6B8170449D86650F ON sales (user_id_id)');
        $this->addSql('CREATE TABLE sessions (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, login_time TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, logout_time TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_9A609D139D86650F ON sessions (user_id_id)');
        $this->addSql('CREATE TABLE stock (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, quantity INT NOT NULL, last_update TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, product_id_id INT NOT NULL, warehouse_id_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_4B365660DE18E50B ON stock (product_id_id)');
        $this->addSql('CREATE INDEX IDX_4B365660FE25E29A ON stock (warehouse_id_id)');
        $this->addSql('CREATE TABLE stock_movements (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(255) NOT NULL, quantity INT NOT NULL, note TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, product_id_id INT NOT NULL, warehouse_id_id INT NOT NULL, user_id_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_A0BE93C9DE18E50B ON stock_movements (product_id_id)');
        $this->addSql('CREATE INDEX IDX_A0BE93C9FE25E29A ON stock_movements (warehouse_id_id)');
        $this->addSql('CREATE INDEX IDX_A0BE93C99D86650F ON stock_movements (user_id_id)');
        $this->addSql('CREATE TABLE suppliers (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, phone VARCHAR(255) NOT NULL, address VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE ticket_messages (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, message TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_5E6BE2179D86650F ON ticket_messages (user_id_id)');
        $this->addSql('CREATE TABLE tickets (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, subject VARCHAR(255) NOT NULL, priority VARCHAR(255) NOT NULL, status VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id_id INT NOT NULL, ticket_messages_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_54469DF49D86650F ON tickets (user_id_id)');
        $this->addSql('CREATE INDEX IDX_54469DF4C9005925 ON tickets (ticket_messages_id)');
        $this->addSql('CREATE TABLE user_notifications (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, read_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id_id INT NOT NULL, notification_id_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8E8E1D839D86650F ON user_notifications (user_id_id)');
        $this->addSql('CREATE INDEX IDX_8E8E1D83B9F07BAE ON user_notifications (notification_id_id)');
        $this->addSql('CREATE TABLE warehouse_transfers (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, quantity INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, product_id_id INT NOT NULL, from_warehouse_id INT NOT NULL, user_id_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_BFBF77A7DE18E50B ON warehouse_transfers (product_id_id)');
        $this->addSql('CREATE INDEX IDX_BFBF77A76DC63638 ON warehouse_transfers (from_warehouse_id)');
        $this->addSql('CREATE INDEX IDX_BFBF77A79D86650F ON warehouse_transfers (user_id_id)');
        $this->addSql('CREATE TABLE warehouses (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, address VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE audit_logs ADD CONSTRAINT FK_D62F28589D86650F FOREIGN KEY (user_id_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE cart_items ADD CONSTRAINT FK_BEF4844520AEF35F FOREIGN KEY (cart_id_id) REFERENCES carts (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE cart_items ADD CONSTRAINT FK_BEF48445DE18E50B FOREIGN KEY (product_id_id) REFERENCES products (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE carts ADD CONSTRAINT FK_4E004AAC9D86650F FOREIGN KEY (user_id_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE carts ADD CONSTRAINT FK_4E004AACB171EB6C FOREIGN KEY (customer_id_id) REFERENCES customers (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE products ADD CONSTRAINT FK_B3BA5A5A9777D11E FOREIGN KEY (category_id_id) REFERENCES categories (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE purchase_items ADD CONSTRAINT FK_35D56A67AB8F1D7D FOREIGN KEY (purchase_id_id) REFERENCES purchases (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE purchase_items ADD CONSTRAINT FK_35D56A67DE18E50B FOREIGN KEY (product_id_id) REFERENCES products (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE purchases ADD CONSTRAINT FK_AA6431FEA65F9C7D FOREIGN KEY (supplier_id_id) REFERENCES suppliers (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE purchases ADD CONSTRAINT FK_AA6431FE9D86650F FOREIGN KEY (user_id_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE role_permissions ADD CONSTRAINT FK_1FBA94E6D60322AC FOREIGN KEY (role_id) REFERENCES roles (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE role_permissions ADD CONSTRAINT FK_1FBA94E6FED90CCA FOREIGN KEY (permission_id) REFERENCES permissions (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE sale_items ADD CONSTRAINT FK_31C2B1CEAF98C6D4 FOREIGN KEY (sale_id_id) REFERENCES sales (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE sale_items ADD CONSTRAINT FK_31C2B1CEDE18E50B FOREIGN KEY (product_id_id) REFERENCES products (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE sales ADD CONSTRAINT FK_6B817044B171EB6C FOREIGN KEY (customer_id_id) REFERENCES customers (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE sales ADD CONSTRAINT FK_6B8170449D86650F FOREIGN KEY (user_id_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE sessions ADD CONSTRAINT FK_9A609D139D86650F FOREIGN KEY (user_id_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE stock ADD CONSTRAINT FK_4B365660DE18E50B FOREIGN KEY (product_id_id) REFERENCES products (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE stock ADD CONSTRAINT FK_4B365660FE25E29A FOREIGN KEY (warehouse_id_id) REFERENCES warehouses (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE stock_movements ADD CONSTRAINT FK_A0BE93C9DE18E50B FOREIGN KEY (product_id_id) REFERENCES products (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE stock_movements ADD CONSTRAINT FK_A0BE93C9FE25E29A FOREIGN KEY (warehouse_id_id) REFERENCES warehouses (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE stock_movements ADD CONSTRAINT FK_A0BE93C99D86650F FOREIGN KEY (user_id_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE ticket_messages ADD CONSTRAINT FK_5E6BE2179D86650F FOREIGN KEY (user_id_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE tickets ADD CONSTRAINT FK_54469DF49D86650F FOREIGN KEY (user_id_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE tickets ADD CONSTRAINT FK_54469DF4C9005925 FOREIGN KEY (ticket_messages_id) REFERENCES ticket_messages (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_notifications ADD CONSTRAINT FK_8E8E1D839D86650F FOREIGN KEY (user_id_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_notifications ADD CONSTRAINT FK_8E8E1D83B9F07BAE FOREIGN KEY (notification_id_id) REFERENCES notifications (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE warehouse_transfers ADD CONSTRAINT FK_BFBF77A7DE18E50B FOREIGN KEY (product_id_id) REFERENCES products (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE warehouse_transfers ADD CONSTRAINT FK_BFBF77A76DC63638 FOREIGN KEY (from_warehouse_id) REFERENCES warehouses (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE warehouse_transfers ADD CONSTRAINT FK_BFBF77A79D86650F FOREIGN KEY (user_id_id) REFERENCES "user" (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE audit_logs DROP CONSTRAINT FK_D62F28589D86650F');
        $this->addSql('ALTER TABLE cart_items DROP CONSTRAINT FK_BEF4844520AEF35F');
        $this->addSql('ALTER TABLE cart_items DROP CONSTRAINT FK_BEF48445DE18E50B');
        $this->addSql('ALTER TABLE carts DROP CONSTRAINT FK_4E004AAC9D86650F');
        $this->addSql('ALTER TABLE carts DROP CONSTRAINT FK_4E004AACB171EB6C');
        $this->addSql('ALTER TABLE products DROP CONSTRAINT FK_B3BA5A5A9777D11E');
        $this->addSql('ALTER TABLE purchase_items DROP CONSTRAINT FK_35D56A67AB8F1D7D');
        $this->addSql('ALTER TABLE purchase_items DROP CONSTRAINT FK_35D56A67DE18E50B');
        $this->addSql('ALTER TABLE purchases DROP CONSTRAINT FK_AA6431FEA65F9C7D');
        $this->addSql('ALTER TABLE purchases DROP CONSTRAINT FK_AA6431FE9D86650F');
        $this->addSql('ALTER TABLE role_permissions DROP CONSTRAINT FK_1FBA94E6D60322AC');
        $this->addSql('ALTER TABLE role_permissions DROP CONSTRAINT FK_1FBA94E6FED90CCA');
        $this->addSql('ALTER TABLE sale_items DROP CONSTRAINT FK_31C2B1CEAF98C6D4');
        $this->addSql('ALTER TABLE sale_items DROP CONSTRAINT FK_31C2B1CEDE18E50B');
        $this->addSql('ALTER TABLE sales DROP CONSTRAINT FK_6B817044B171EB6C');
        $this->addSql('ALTER TABLE sales DROP CONSTRAINT FK_6B8170449D86650F');
        $this->addSql('ALTER TABLE sessions DROP CONSTRAINT FK_9A609D139D86650F');
        $this->addSql('ALTER TABLE stock DROP CONSTRAINT FK_4B365660DE18E50B');
        $this->addSql('ALTER TABLE stock DROP CONSTRAINT FK_4B365660FE25E29A');
        $this->addSql('ALTER TABLE stock_movements DROP CONSTRAINT FK_A0BE93C9DE18E50B');
        $this->addSql('ALTER TABLE stock_movements DROP CONSTRAINT FK_A0BE93C9FE25E29A');
        $this->addSql('ALTER TABLE stock_movements DROP CONSTRAINT FK_A0BE93C99D86650F');
        $this->addSql('ALTER TABLE ticket_messages DROP CONSTRAINT FK_5E6BE2179D86650F');
        $this->addSql('ALTER TABLE tickets DROP CONSTRAINT FK_54469DF49D86650F');
        $this->addSql('ALTER TABLE tickets DROP CONSTRAINT FK_54469DF4C9005925');
        $this->addSql('ALTER TABLE user_notifications DROP CONSTRAINT FK_8E8E1D839D86650F');
        $this->addSql('ALTER TABLE user_notifications DROP CONSTRAINT FK_8E8E1D83B9F07BAE');
        $this->addSql('ALTER TABLE warehouse_transfers DROP CONSTRAINT FK_BFBF77A7DE18E50B');
        $this->addSql('ALTER TABLE warehouse_transfers DROP CONSTRAINT FK_BFBF77A76DC63638');
        $this->addSql('ALTER TABLE warehouse_transfers DROP CONSTRAINT FK_BFBF77A79D86650F');
        $this->addSql('DROP TABLE audit_logs');
        $this->addSql('DROP TABLE cart_items');
        $this->addSql('DROP TABLE carts');
        $this->addSql('DROP TABLE customers');
        $this->addSql('DROP TABLE notifications');
        $this->addSql('DROP TABLE permissions');
        $this->addSql('DROP TABLE products');
        $this->addSql('DROP TABLE purchase_items');
        $this->addSql('DROP TABLE purchases');
        $this->addSql('DROP TABLE role_permissions');
        $this->addSql('DROP TABLE sale_items');
        $this->addSql('DROP TABLE sales');
        $this->addSql('DROP TABLE sessions');
        $this->addSql('DROP TABLE stock');
        $this->addSql('DROP TABLE stock_movements');
        $this->addSql('DROP TABLE suppliers');
        $this->addSql('DROP TABLE ticket_messages');
        $this->addSql('DROP TABLE tickets');
        $this->addSql('DROP TABLE user_notifications');
        $this->addSql('DROP TABLE warehouse_transfers');
        $this->addSql('DROP TABLE warehouses');
    }
}
